import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const _localizedValues = {
    'en': {
      'app_title': 'Discover Spaces',
      'onboarding_title_1': 'Discover amazing places',
      'onboarding_desc_1': 'Browse curated real estate and spaces with immersive previews.',
      'onboarding_title_2': 'Smart search & filters',
      'onboarding_desc_2': 'Find the perfect match with smart search, filters, and categories.',
      'onboarding_title_3': 'Compare & visualize',
      'onboarding_desc_3': 'Compare items, see 3D hints, and get AI info soon.',
      'skip': 'Skip',
      'next': 'Next',
      'back': 'Back',
      'get_started': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot password?',
      'login_as_guest': 'Continue as guest',
      'home': 'Home',
      'catalog': 'Catalog',
      'compare': 'Compare',
      'profile': 'Profile',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'primary_color': 'Primary color',
      'dark_mode': 'Dark mode',
      'light_mode': 'Light mode',
      'search': 'Search',
      'save_search': 'Save search',
      'save_search_hint': 'Save this search to revisit and get reminders.',
      'saved_searches': 'Saved searches',
      'search_saved': 'Search saved',
      'remove_saved_search': 'Remove saved search',
      'filters': 'Filters',
      'no_results_found': 'No results found',
      'add_to_favorites': 'Add to favorites',
      'add_to_compare': 'Add to compare',
      'ai_info': 'AI Info',
      'sort': 'Sort',
      'sort_recent': 'Newest first',
      'sort_price_low_high': 'Price: low to high',
      'sort_price_high_low': 'Price: high to low',
      'recent_searches': 'Recent searches',
      'clear_history': 'Clear history',
      'recently_viewed': 'Recently viewed',
      'recently_viewed_empty': 'You have not viewed any items yet.',
      'coming_soon': 'Coming soon',
      'login_welcome': 'Welcome back',
      'password_strength': 'Password strength',
      'reset_password': 'Reset password',
      'reset_instructions': 'Enter your email to receive reset instructions.',
      'submit': 'Submit',
      'theme_mode': 'Theme Mode',
      'language_title': 'Language',
      'primary_color_title': 'Primary Color',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all as read',
      'ai_info_placeholder': 'AI-powered descriptions are coming soon.',
      'explore': 'Explore',
      'view_all': 'View all',
      'favorites': 'Favorites',
      'add': 'Add',
      'remove': 'Remove',
      'empty_compare_title': "You haven't added any items to compare yet.",
      'go_home': 'Go Home',
      'items_for_you': 'Items for you',
      'price': 'Price',
      'location': 'Location',
      'type': 'Type',
      'rooms': 'Rooms',
      'ai_info_button': 'AI Info',
      'logout': 'Logout',
      'guest': 'Continue as guest',
      'passwords_do_not_match': 'Passwords do not match',
      'invalid_email': 'Please enter a valid email',
      'password_too_short': 'Password is too short',
      'strength_weak': 'Weak',
      'strength_ok': 'Okay',
      'strength_strong': 'Strong',
      'done': 'Done',
      'refresh': 'Pull to refresh',
      'filter_categories': 'Categories',
      'filter_city': 'City',
      'filter_price': 'Price range',
      'apply_filters': 'Apply filters',
      'clear': 'Clear',
      'compare_now': 'Compare now',
      'remove_item': 'Remove item',
      'ai_info_headline': 'AI insight',
      'favorites_empty_title': 'No favorites yet',
      'favorites_empty_body': 'Save homes you love to compare, revisit, and share later.',
      'browse_catalog': 'Browse catalog',
      'all_caught_up': "You're all caught up!",
      'all_caught_up_desc': 'We will drop notifications here when new previews arrive.',
      'ai_info_steps_title': 'How AI info will work soon',
      'ai_info_step_collect': 'Collect highlights from listing photos and attributes.',
      'ai_info_step_summarize': 'Summarize selling points and nearby amenities.',
      'ai_info_step_translate': 'Offer instant bilingual Arabic/English narratives.',
      'schedule_visit': 'Schedule a visit',
      'select_date': 'Select date',
      'select_time': 'Select time',
      'note_optional': 'Add note (optional)',
      'visit_saved': 'Visit saved',
      'upcoming_visits': 'Upcoming visits',
      'no_upcoming_visits': 'No visits scheduled yet',
      'cancel_visit': 'Cancel visit',
      'visit_reminder': 'Visit reminders',
    },
    'ar': {
      'app_title': 'اكتشف المساحات',
      'onboarding_title_1': 'اكتشف أماكن مذهلة',
      'onboarding_desc_1': 'تصفح عقارات ومساحات مختارة مع معاينات غامرة.',
      'onboarding_title_2': 'بحث وفلاتر ذكية',
      'onboarding_desc_2': 'اعثر على الخيار المناسب عبر البحث الذكي والفئات.',
      'onboarding_title_3': 'قارن وتخيّل',
      'onboarding_desc_3': 'قارن العناصر، شاهد تلميحات ثلاثية الأبعاد، والمزيد قريباً.',
      'skip': 'تخطي',
      'next': 'التالي',
      'back': 'السابق',
      'get_started': 'البدء',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_as_guest': 'الدخول كضيف',
      'home': 'الرئيسية',
      'catalog': 'الكتالوج',
      'compare': 'المقارنة',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'theme': 'المظهر',
      'language': 'اللغة',
      'primary_color': 'اللون الرئيسي',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'search': 'بحث',
      'save_search': 'حفظ البحث',
      'save_search_hint': 'احفظ هذا البحث للعودة إليه والحصول على تنبيهات محلية.',
      'saved_searches': 'عمليات البحث المحفوظة',
      'search_saved': 'تم حفظ البحث',
      'remove_saved_search': 'إزالة البحث المحفوظ',
      'filters': 'فلاتر',
      'no_results_found': 'لا توجد نتائج',
      'add_to_favorites': 'إضافة للمفضلة',
      'add_to_compare': 'إضافة للمقارنة',
      'ai_info': 'معلومات الذكاء الاصطناعي',
      'sort': 'ترتيب',
      'sort_recent': 'الأحدث أولاً',
      'sort_price_low_high': 'السعر: من الأقل إلى الأعلى',
      'sort_price_high_low': 'السعر: من الأعلى إلى الأقل',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear_history': 'مسح السجل',
      'recently_viewed': 'شوهد مؤخراً',
      'recently_viewed_empty': 'لم تقم بمشاهدة أي عناصر بعد.',
      'coming_soon': 'قريباً',
      'login_welcome': 'مرحباً بعودتك',
      'password_strength': 'قوة كلمة المرور',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_instructions': 'أدخل بريدك الإلكتروني لتصلك التعليمات.',
      'submit': 'إرسال',
      'theme_mode': 'وضع المظهر',
      'language_title': 'اللغة',
      'primary_color_title': 'اللون الرئيسي',
      'notifications': 'الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'ai_info_placeholder': 'وصف يعتمد على الذكاء الاصطناعي سيصل قريباً.',
      'explore': 'استكشف',
      'view_all': 'عرض الكل',
      'favorites': 'المفضلة',
      'add': 'إضافة',
      'remove': 'إزالة',
      'empty_compare_title': 'لم تقم بإضافة أي عنصر للمقارنة بعد.',
      'go_home': 'العودة للرئيسية',
      'items_for_you': 'عناصر لك',
      'price': 'السعر',
      'location': 'الموقع',
      'type': 'النوع',
      'rooms': 'الغرف',
      'ai_info_button': 'معلومات باستخدام الذكاء الاصطناعي',
      'logout': 'تسجيل الخروج',
      'guest': 'المتابعة كضيف',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'invalid_email': 'الرجاء إدخال بريد صحيح',
      'password_too_short': 'كلمة المرور قصيرة',
      'strength_weak': 'ضعيفة',
      'strength_ok': 'جيدة',
      'strength_strong': 'قوية',
      'done': 'تم',
      'refresh': 'اسحب للتحديث',
      'filter_categories': 'الفئات',
      'filter_city': 'المدينة',
      'filter_price': 'نطاق السعر',
      'apply_filters': 'تطبيق الفلاتر',
      'clear': 'إعادة التعيين',
      'compare_now': 'ابدأ المقارنة',
      'remove_item': 'إزالة العنصر',
      'ai_info_headline': 'لمحة ذكاء اصطناعي',
      'favorites_empty_title': 'لا توجد مفضلات بعد',
      'favorites_empty_body': 'احفظ المساحات المفضلة للمقارنة والعودة إليها لاحقاً.',
      'browse_catalog': 'تصفح الكتالوج',
      'all_caught_up': 'لا إشعارات جديدة',
      'all_caught_up_desc': 'سنخبرك هنا عندما تتوفر معاينات أو تحديثات جديدة.',
      'ai_info_steps_title': 'كيف ستعمل ميزة الذكاء الاصطناعي قريباً',
      'ai_info_step_collect': 'جمع أبرز المعلومات من الصور والخصائص.',
      'ai_info_step_summarize': 'تلخيص نقاط التميز والمرافق القريبة.',
      'ai_info_step_translate': 'تقديم وصف فوري بالعربية والإنجليزية.',
      'schedule_visit': 'جدولة زيارة',
      'select_date': 'اختيار التاريخ',
      'select_time': 'اختيار الوقت',
      'note_optional': 'ملاحظة (اختياري)',
      'visit_saved': 'تم حفظ الزيارة',
      'upcoming_visits': 'الزيارات القادمة',
      'no_upcoming_visits': 'لا توجد زيارات مجدولة بعد',
      'cancel_visit': 'إلغاء الزيارة',
      'visit_reminder': 'تذكيرات الزيارة',
    }
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('ar'), Locale('en')];
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
