import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const _localizedValues = {
    'en': {
      'app_title': 'Discover Spaces',
      'onboarding_title_1': 'Discover amazing places',
      'onboarding_desc_1': 'Browse curated real estate and spaces with immersive previews.',
      'onboarding_title_2': 'Smart search & filters',
      'onboarding_desc_2': 'Find the perfect match with smart search, filters, and categories.',
      'onboarding_title_3': 'Compare & visualize',
      'onboarding_desc_3': 'Compare items, see 3D hints, and get AI info soon.',
      'skip': 'Skip',
      'next': 'Next',
      'back': 'Back',
      'get_started': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot password?',
      'login_as_guest': 'Continue as guest',
      'home': 'Home',
      'catalog': 'Catalog',
      'compare': 'Compare',
      'profile': 'Profile',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'primary_color': 'Primary color',
      'dark_mode': 'Dark mode',
      'light_mode': 'Light mode',
      'system_mode': 'Use system setting',
      'text_size': 'Text size',
      'text_size_hint': 'Adjust interface scale for comfortable reading.',
      'compact_cards': 'Compact cards',
      'compact_cards_hint': 'Show tighter item cards for dense browsing.',
      'grid_view': 'Grid view',
      'list_view': 'List view',
      'layout_mode': 'Layout mode',
      'high_contrast': 'High contrast',
      'high_contrast_hint': 'Boost clarity for cards and chips with stronger contrast.',
      'reduce_motion': 'Reduce motion',
      'reduce_motion_hint': 'Minimize screen transitions for calmer navigation.',
      'search': 'Search',
      'save_search': 'Save search',
      'save_search_hint': 'Save this search to revisit and get reminders.',
      'saved_searches': 'Saved searches',
      'search_saved': 'Search saved',
      'remove_saved_search': 'Remove saved search',
      'filters': 'Filters',
      'no_results_found': 'No results found',
      'add_to_favorites': 'Add to favorites',
      'add_to_compare': 'Add to compare',
      'ai_info': 'AI Info',
      'sort': 'Sort',
      'sort_recent': 'Newest first',
      'sort_price_low_high': 'Price: low to high',
      'sort_price_high_low': 'Price: high to low',
      'recent_searches': 'Recent searches',
      'clear_history': 'Clear history',
      'recently_viewed': 'Recently viewed',
      'recently_viewed_empty': 'You have not viewed any items yet.',
      'coming_soon': 'Coming soon',
      'login_welcome': 'Welcome back',
      'password_strength': 'Password strength',
      'reset_password': 'Reset password',
      'reset_instructions': 'Enter your email to receive reset instructions.',
      'submit': 'Submit',
      'theme_mode': 'Theme Mode',
      'language_title': 'Language',
      'primary_color_title': 'Primary Color',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all as read',
      'ai_info_placeholder': 'AI-powered descriptions are coming soon.',
      'explore': 'Explore',
      'view_all': 'View all',
      'favorites': 'Favorites',
      'add': 'Add',
      'added': 'Added',
      'remove': 'Remove',
      'empty_compare_title': "You haven't added any items to compare yet.",
      'go_home': 'Go Home',
      'items_for_you': 'Items for you',
      'new': 'New',
      'price': 'Price',
      'location': 'Location',
      'type': 'Type',
      'rooms': 'Rooms',
      'baths': 'Baths',
      'area': 'Area',
      'rating': 'Rating',
      'note': 'Note',
      'notes': 'Notes',
      'my_notes': 'My notes',
      'add_note': 'Add note',
      'edit_note': 'Edit note',
      'note_hint': 'Store private highlights, ideas, or next steps.',
      'note_saved': 'Note saved',
      'note_removed': 'Note removed',
      'activity': 'Activity',
      'ai_info_button': 'AI Info',
      'logout': 'Logout',
      'guest': 'Continue as guest',
      'passwords_do_not_match': 'Passwords do not match',
      'invalid_email': 'Please enter a valid email',
      'password_too_short': 'Password is too short',
      'strength_weak': 'Weak',
      'strength_ok': 'Okay',
      'strength_strong': 'Strong',
      'done': 'Done',
      'refresh': 'Pull to refresh',
      'filter_categories': 'Categories',
      'filter_city': 'City',
      'filter_price': 'Price range',
      'apply_filters': 'Apply filters',
      'clear': 'Clear',
      'compare_now': 'Compare now',
      'remove_item': 'Remove item',
      'ai_info_headline': 'AI insight',
      'favorites_empty_title': 'No favorites yet',
      'favorites_empty_body': 'Save homes you love to compare, revisit, and share later.',
      'browse_catalog': 'Browse catalog',
      'all_caught_up': "You're all caught up!",
      'all_caught_up_desc': 'We will drop notifications here when new previews arrive.',
      'ai_info_steps_title': 'How AI info will work soon',
      'ai_info_step_collect': 'Collect highlights from listing photos and attributes.',
      'ai_info_step_summarize': 'Summarize selling points and nearby amenities.',
      'ai_info_step_translate': 'Offer instant bilingual Arabic/English narratives.',
      'schedule_visit': 'Schedule a visit',
      'saved_search_matches': 'Saved search matches',
      'view_matches': 'View matches',
      'no_saved_searches': 'No saved searches yet',
      'no_matches_yet': 'No matches yet — tweak filters to see results.',
      'apply_search': 'Apply search',
      'select_date': 'Select date',
      'select_time': 'Select time',
      'note_optional': 'Add note (optional)',
      'visit_saved': 'Visit saved',
      'upcoming_visits': 'Upcoming visits',
      'no_upcoming_visits': 'No visits scheduled yet',
      'cancel_visit': 'Cancel visit',
      'visit_reminder': 'Visit reminders',
      'data_and_storage': 'Data & storage',
      'clear_cached_data': 'Clear saved data',
      'clear_cached_data_desc': 'Remove favorites, recents, saved searches, and scheduled visits from this device.',
      'data_cleared': 'Saved data removed',
      'matches_for_you': 'Matches for you',
      'help_center': 'Help center',
      'guides': 'Guides & tips',
      'about_app': 'About the app',
      'support_desc': 'Get quick answers, best practices, and how to get help.',
      'contact_support': 'Contact support',
      'support_email': 'support@discover.fake',
      'copy_email': 'Copy email',
      'email_copied': 'Support email copied',
      'support_hours': 'We reply within local working hours.',
      'feedback': 'Feedback',
      'share_feedback': 'Share feedback',
      'feedback_intro': 'Tell us what is working well and where we can polish the experience.',
      'satisfaction': 'Overall satisfaction',
      'feedback_topics': 'Topics',
      'topic_ui': 'Design & usability',
      'topic_data': 'Data quality',
      'topic_performance': 'Performance',
      'topic_other': 'Something else',
      'feedback_note_hint': 'Share quick notes or ideas (stored locally only).',
      'feedback_saved': 'Feedback saved on device',
      'feedback_cleared': 'Feedback removed',
      'latest_feedback': 'Latest feedback',
      'send_feedback': 'Send feedback',
      'whats_new': "What's new",
      'view_changelog': 'View changelog',
      'release_notes': 'Release notes',
      'release_highlights': 'Highlights in this update',
      'safety_tips': 'Safety tips',
      'safety_title': 'Stay safe when touring',
      'safety_point_1': 'Confirm appointments and meet in public lobbies first.',
      'safety_point_2': 'Share your visit schedule with a friend or family member.',
      'safety_point_3': 'Verify property details before committing to payments.',
      'data_snapshot': 'Data snapshot',
      'copy_snapshot': 'Copy snapshot',
      'snapshot_copied': 'Snapshot copied to clipboard',
      'last_updated': 'Last updated',
      'today': 'Today',
      'faq': 'Common questions',
      'faq_search': 'How do I find better matches?',
      'faq_search_ans': 'Use filters by city, price, and type. Save searches to revisit quickly.',
      'faq_compare': 'How does comparison work?',
      'faq_compare_ans': 'Add items to compare to see specs side by side on the Compare tab.',
      'faq_visits': 'Can I schedule visits?',
      'faq_visits_ans': 'Open a listing and tap “Schedule a visit” to pick your slot and keep reminders.',
      'faq_data': 'How do I clear my saved data?',
      'faq_data_ans': 'Use Settings > Data & storage to wipe favorites, history, and saved searches.',
      'app_shortcuts': 'Shortcuts',
      'open_settings': 'Open settings',
      'view_guides': 'View guides',
      'support_articles': 'Suggested reading',
      'guide_explore': 'Explore faster with categories, saved searches, and map previews.',
      'guide_compare': 'Use compare to highlight differences before shortlisting.',
      'guide_visits': 'Schedule and manage visits with reminders.',
      'guide_notes': 'Add private notes to remember details you care about.',
      'about_story': 'Built to make exploring spaces delightful, bilingual, and personal.',
      'about_values': 'Privacy-first: all data stays on device until you choose otherwise.',
      'about_version': 'Version',
      'roadmap': 'Roadmap',
      'roadmap_ai': 'AI narratives and smarter suggestions.',
      'roadmap_personalization': 'Deeper personalization powered by your preferences.',
      'roadmap_offline': 'Offline-friendly browsing for saved items.',
      'send_feedback': 'Send feedback',
      'feedback_stub': 'Share your ideas so we can prioritize the next wave of features.',
      'settings_shortcut': 'Settings shortcut',
      'help_tip': 'Need help configuring the experience?',
      'guides_tip': 'See walkthroughs and best practices.',
      'about_team': 'Made for curious explorers across Arabic and English.',
      'more_to_explore': 'More to explore',
      'read_more': 'Read more',
      'journey_planner': 'Journey planner',
      'journey_progress': 'Journey progress',
      'journey_progress_hint': 'Track your checklist from research to closing.',
      'journey_steps_completed': 'Steps done',
      'journey_actions': 'Steps to finish',
      'reset_plan': 'Reset plan',
      'step_research': 'Research & inspiration',
      'step_research_desc': 'Browse categories, saved searches, and guides.',
      'step_shortlist': 'Shortlist favorites',
      'step_shortlist_desc': 'Compare items, save notes, and refine your list.',
      'step_schedule': 'Schedule visits',
      'step_schedule_desc': 'Pick time slots and keep reminders locally.',
      'step_notes': 'Capture notes',
      'step_notes_desc': 'Write your impressions per item to decide faster.',
      'step_finalize': 'Finalize choice',
      'step_finalize_desc': 'Lock in your pick, revisit legal and safety tips.',
      'budget_planner': 'Budget planner',
      'budget_hint': 'Keep your targets in mind while filtering by price.',
      'budget_target': 'Monthly target',
      'budget_cta': 'Adjust any time — stored on this device.',
      'planning_tools': 'Planning tools',
      'planning_intro': 'Use local checklists and calculators to stay organized.',
      'readiness_checklist': 'Readiness checklist',
      'readiness_intro': 'Stay organized with documents, visits, and budget before deciding.',
      'checklist_progress': 'Checklist progress',
      'reset_checklist': 'Reset checklist',
      'task_finance': 'Confirm finances',
      'task_finance_desc': 'Align your budget, savings, and approvals before touring.',
      'task_documents': 'Prepare documents',
      'task_documents_desc': 'Keep IDs, proof of funds, and key notes ready to share.',
      'task_visit_plan': 'Plan visits',
      'task_visit_plan_desc': 'Group visits by city and time to make the most of your day.',
      'task_review': 'Review & decide',
      'task_review_desc': 'Revisit notes, ratings, and comparisons before making an offer.',
      'affordability_calculator': 'Affordability calculator',
      'home_price': 'Home price',
      'down_payment': 'Down payment %',
      'interest_rate': 'Interest rate',
      'loan_years': 'Loan years',
      'estimated_payment': 'Est. monthly payment',
      'calculator_hint': 'Adjust the sliders to explore what feels comfortable.',
      'within_budget': 'Within your budget target',
      'over_budget': 'Above your budget target',
      'recommendations': 'Matches in your range',
      'no_recommendations': 'No matches in this range yet',
      'open_checklist': 'Open checklist',
      'calculator_shortcut': 'Calculator',
      'readiness_shortcut': 'Readiness',
      'apply_numbers': 'Apply numbers',
      'recent_progress': 'Recent momentum',
      'open_insights': 'Open insights',
      'insights': 'Insights',
      'insights_subtitle': 'Monitor saved data, visits, and budget readiness.',
      'city_focus': 'City focus',
      'average_rating': 'Average rating',
      'listings_count': '{count} listings',
      'budget_vs_filters': 'Budget vs filters',
      'budget_alignment': 'Compare your target against your current filters.',
      'price_window': 'Price window',
      'recent_activity': 'Recent activity',
      'insights_empty_recent': 'No recent browsing yet',
      'launch_journey': 'Open journey planner',
      'notes_section': 'My notes',
      'no_visits': 'No visits logged yet',
      'app_health': 'App health & tips',
      'support_status': 'All systems normal — no backend required today.',
      'legal_and_privacy': 'Legal & privacy',
      'privacy_policy': 'Privacy policy',
      'privacy_body': 'We keep your browsing, preferences, and feedback on this device only.',
      'privacy_local': 'No external servers — your data lives locally.',
      'privacy_saved': 'You can clear saved data anytime from Settings.',
      'privacy_contact': 'Use support requests to ask questions about data handling.',
      'terms_of_use': 'Terms of use',
      'terms_body': 'Use the app responsibly with mock data while we prepare future services.',
      'terms_usage': 'Content is illustrative and should not be treated as real listings.',
      'terms_content': 'Do not misuse images or texts; they are placeholders.',
      'terms_changes': 'Features and terms may change as we iterate.',
      'safety_and_trust': 'Safety & trust',
      'safety_body': 'Stay mindful when touring, meeting, or sharing personal details.',
      'safety_expectations': 'Confirm meetings and prefer public spaces first.',
      'safety_reporting': 'Report suspicious behavior through a support request.',
      'safety_updates': 'We update tips regularly to reflect best practices.',
      'support_requests': 'Support requests',
      'new_request': 'New request',
      'request_title': 'Subject',
      'request_topic': 'Topic',
      'request_details': 'Details',
      'support_request_hint': 'Share what you need help with — stays on your device.',
      'request_details_hint': 'Please add at least a few words.',
      'request_saved': 'Request saved locally',
      'request_removed': 'Request removed',
      'support_empty_title': 'No support notes yet',
      'support_empty_body': 'Track support needs or questions here without leaving the app.',
      'mark_resolved': 'Mark resolved',
      'mark_pending': 'Mark pending',
      'required_field': 'This field is required',
      'send': 'Send',
    },
    'ar': {
      'app_title': 'اكتشف المساحات',
      'onboarding_title_1': 'اكتشف أماكن مذهلة',
      'onboarding_desc_1': 'تصفح عقارات ومساحات مختارة مع معاينات غامرة.',
      'onboarding_title_2': 'بحث وفلاتر ذكية',
      'onboarding_desc_2': 'اعثر على الخيار المناسب عبر البحث الذكي والفئات.',
      'onboarding_title_3': 'قارن وتخيّل',
      'onboarding_desc_3': 'قارن العناصر، شاهد تلميحات ثلاثية الأبعاد، والمزيد قريباً.',
      'skip': 'تخطي',
      'next': 'التالي',
      'back': 'السابق',
      'get_started': 'البدء',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_as_guest': 'الدخول كضيف',
      'home': 'الرئيسية',
      'catalog': 'الكتالوج',
      'compare': 'المقارنة',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'theme': 'المظهر',
      'language': 'اللغة',
      'primary_color': 'اللون الرئيسي',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'system_mode': 'اتباع إعداد النظام',
      'text_size': 'حجم النص',
      'text_size_hint': 'اضبط حجم الواجهة لقراءة مريحة.',
      'compact_cards': 'بطاقات مضغوطة',
      'compact_cards_hint': 'عرض البطاقات بشكل أكثر إحكاماً لزيادة المحتوى.',
      'grid_view': 'عرض شبكي',
      'list_view': 'عرض قائمة',
      'layout_mode': 'وضع التخطيط',
      'high_contrast': 'تباين عالٍ',
      'high_contrast_hint': 'زيادة وضوح البطاقات والشرائح بتباين أقوى.',
      'reduce_motion': 'تقليل الحركة',
      'reduce_motion_hint': 'تقليل الانتقالات لملاحة أكثر هدوءاً.',
      'search': 'بحث',
      'save_search': 'حفظ البحث',
      'save_search_hint': 'احفظ هذا البحث للعودة إليه والحصول على تنبيهات محلية.',
      'saved_searches': 'عمليات البحث المحفوظة',
      'search_saved': 'تم حفظ البحث',
      'remove_saved_search': 'إزالة البحث المحفوظ',
      'filters': 'فلاتر',
      'no_results_found': 'لا توجد نتائج',
      'add_to_favorites': 'إضافة للمفضلة',
      'add_to_compare': 'إضافة للمقارنة',
      'ai_info': 'معلومات الذكاء الاصطناعي',
      'sort': 'ترتيب',
      'sort_recent': 'الأحدث أولاً',
      'sort_price_low_high': 'السعر: من الأقل إلى الأعلى',
      'sort_price_high_low': 'السعر: من الأعلى إلى الأقل',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear_history': 'مسح السجل',
      'recently_viewed': 'شوهد مؤخراً',
      'recently_viewed_empty': 'لم تقم بمشاهدة أي عناصر بعد.',
      'coming_soon': 'قريباً',
      'login_welcome': 'مرحباً بعودتك',
      'password_strength': 'قوة كلمة المرور',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_instructions': 'أدخل بريدك الإلكتروني لتصلك التعليمات.',
      'submit': 'إرسال',
      'theme_mode': 'وضع المظهر',
      'language_title': 'اللغة',
      'primary_color_title': 'اللون الرئيسي',
      'notifications': 'الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'ai_info_placeholder': 'وصف يعتمد على الذكاء الاصطناعي سيصل قريباً.',
      'explore': 'استكشف',
      'view_all': 'عرض الكل',
      'favorites': 'المفضلة',
      'add': 'إضافة',
      'added': 'تمت الإضافة',
      'remove': 'إزالة',
      'empty_compare_title': 'لم تقم بإضافة أي عنصر للمقارنة بعد.',
      'go_home': 'العودة للرئيسية',
      'items_for_you': 'عناصر لك',
      'new': 'جديد',
      'price': 'السعر',
      'location': 'الموقع',
      'type': 'النوع',
      'rooms': 'الغرف',
      'baths': 'دورات المياه',
      'area': 'المساحة',
      'rating': 'التقييم',
      'note': 'ملاحظة',
      'notes': 'ملاحظات',
      'my_notes': 'ملاحظاتي',
      'add_note': 'إضافة ملاحظة',
      'edit_note': 'تعديل الملاحظة',
      'note_hint': 'اكتب الأفكار أو النقاط المهمة الخاصة بك هنا.',
      'note_saved': 'تم حفظ الملاحظة',
      'note_removed': 'تم حذف الملاحظة',
      'activity': 'النشاط',
      'ai_info_button': 'معلومات باستخدام الذكاء الاصطناعي',
      'logout': 'تسجيل الخروج',
      'guest': 'المتابعة كضيف',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'invalid_email': 'الرجاء إدخال بريد صحيح',
      'password_too_short': 'كلمة المرور قصيرة',
      'strength_weak': 'ضعيفة',
      'strength_ok': 'جيدة',
      'strength_strong': 'قوية',
      'done': 'تم',
      'refresh': 'اسحب للتحديث',
      'filter_categories': 'الفئات',
      'filter_city': 'المدينة',
      'filter_price': 'نطاق السعر',
      'apply_filters': 'تطبيق الفلاتر',
      'clear': 'إعادة التعيين',
      'compare_now': 'ابدأ المقارنة',
      'remove_item': 'إزالة العنصر',
      'ai_info_headline': 'لمحة ذكاء اصطناعي',
      'favorites_empty_title': 'لا توجد مفضلات بعد',
      'favorites_empty_body': 'احفظ المساحات المفضلة للمقارنة والعودة إليها لاحقاً.',
      'browse_catalog': 'تصفح الكتالوج',
      'all_caught_up': 'لا إشعارات جديدة',
      'all_caught_up_desc': 'سنخبرك هنا عندما تتوفر معاينات أو تحديثات جديدة.',
      'ai_info_steps_title': 'كيف ستعمل ميزة الذكاء الاصطناعي قريباً',
      'ai_info_step_collect': 'جمع أبرز المعلومات من الصور والخصائص.',
      'ai_info_step_summarize': 'تلخيص نقاط التميز والمرافق القريبة.',
      'ai_info_step_translate': 'تقديم وصف فوري بالعربية والإنجليزية.',
      'schedule_visit': 'جدولة زيارة',
      'saved_search_matches': 'تطابقات البحث المحفوظ',
      'view_matches': 'عرض التطابقات',
      'no_saved_searches': 'لا توجد عمليات بحث محفوظة بعد',
      'no_matches_yet': 'لا توجد تطابقات حالياً، جرّب تعديل الفلاتر.',
      'apply_search': 'تطبيق البحث',
      'select_date': 'اختيار التاريخ',
      'select_time': 'اختيار الوقت',
      'note_optional': 'ملاحظة (اختياري)',
      'visit_saved': 'تم حفظ الزيارة',
      'upcoming_visits': 'الزيارات القادمة',
      'no_upcoming_visits': 'لا توجد زيارات مجدولة بعد',
      'cancel_visit': 'إلغاء الزيارة',
      'visit_reminder': 'تذكيرات الزيارة',
      'data_and_storage': 'البيانات والتخزين',
      'clear_cached_data': 'مسح البيانات المحفوظة',
      'clear_cached_data_desc': 'سيتم إزالة المفضلة والتاريخ والبحث المحفوظ والزيارات المجدولة من هذا الجهاز.',
      'data_cleared': 'تم مسح البيانات المحفوظة',
      'matches_for_you': 'تطابقات مقترحة لك',
      'help_center': 'مركز المساعدة',
      'guides': 'الإرشادات والنصائح',
      'about_app': 'حول التطبيق',
      'support_desc': 'احصل على إجابات سريعة وأفضل الممارسات وخيارات المساعدة.',
      'contact_support': 'تواصل مع الدعم',
      'support_email': 'support@discover.fake',
      'copy_email': 'نسخ البريد',
      'email_copied': 'تم نسخ بريد الدعم',
      'support_hours': 'نرد خلال ساعات العمل المحلية.',
      'feedback': 'ملاحظاتك',
      'share_feedback': 'أرسل ملاحظاتك',
      'feedback_intro': 'أخبرنا بما يعجبك وما يحتاج لتحسين لنصقل التجربة.',
      'satisfaction': 'مدى الرضا',
      'feedback_topics': 'الموضوعات',
      'topic_ui': 'التصميم وسهولة الاستخدام',
      'topic_data': 'جودة البيانات',
      'topic_performance': 'الأداء',
      'topic_other': 'أخرى',
      'feedback_note_hint': 'اكتب ملاحظات أو أفكار سريعة (محفوظة محلياً فقط).',
      'feedback_saved': 'تم حفظ الملاحظات على الجهاز',
      'feedback_cleared': 'تم حذف الملاحظات',
      'latest_feedback': 'أحدث ملاحظاتك',
      'send_feedback': 'إرسال الملاحظات',
      'whats_new': 'ما الجديد',
      'view_changelog': 'عرض سجل التحديثات',
      'release_notes': 'ملاحظات الإصدار',
      'release_highlights': 'أبرز ما في هذا التحديث',
      'safety_tips': 'نصائح للسلامة',
      'safety_title': 'ابق آمناً أثناء الزيارات',
      'safety_point_1': 'أكد المواعيد وقابل في ردهات عامة أولاً.',
      'safety_point_2': 'شارك جدول زياراتك مع صديق أو أحد العائلة.',
      'safety_point_3': 'تحقق من تفاصيل العقار قبل أي دفعات.',
      'data_snapshot': 'لقطة بيانات',
      'copy_snapshot': 'نسخ اللقطة',
      'snapshot_copied': 'تم نسخ اللقطة إلى الحافظة',
      'last_updated': 'آخر تحديث',
      'today': 'اليوم',
      'faq': 'أسئلة شائعة',
      'faq_search': 'كيف أحصل على نتائج أفضل؟',
      'faq_search_ans': 'استخدم فلاتر المدينة والسعر والنوع. احفظ البحث للعودة إليه بسرعة.',
      'faq_compare': 'كيف تعمل المقارنة؟',
      'faq_compare_ans': 'أضف العناصر إلى المقارنة لرؤية المواصفات جنباً إلى جنب في صفحة المقارنة.',
      'faq_visits': 'هل يمكنني جدولة زيارات؟',
      'faq_visits_ans': 'نعم، افتح العنصر واضغط "جدولة زيارة" لاختيار الوقت وتفعيل التذكيرات.',
      'faq_data': 'كيف أمسح بياناتي المحفوظة؟',
      'faq_data_ans': 'استخدم الإعدادات > البيانات والتخزين لمسح المفضلة والسجل والبحث المحفوظ.',
      'app_shortcuts': 'اختصارات',
      'open_settings': 'فتح الإعدادات',
      'view_guides': 'عرض الإرشادات',
      'support_articles': 'قراءة مقترحة',
      'guide_explore': 'استكشف أسرع عبر الفئات، والبحث المحفوظ، ومعاينات الخريطة.',
      'guide_compare': 'استخدم المقارنة لإبراز الفروقات قبل الاختيار النهائي.',
      'guide_visits': 'جدول الزيارات وأدرها مع التذكيرات.',
      'guide_notes': 'أضف ملاحظات خاصة لتتذكر التفاصيل المهمة.',
      'about_story': 'صممنا التطبيق لتجربة استكشاف ممتعة، ثنائية اللغة، وشخصية.',
      'about_values': 'الخصوصية أولاً: تبقى بياناتك على الجهاز ما لم تختر غير ذلك.',
      'about_version': 'الإصدار',
      'roadmap': 'خريطة الطريق',
      'roadmap_ai': 'سرد قصصي بالذكاء الاصطناعي واقتراحات أذكى.',
      'roadmap_personalization': 'تخصيص أعمق بناءً على تفضيلاتك.',
      'roadmap_offline': 'تصفح أوفلاين للعناصر المحفوظة.',
      'send_feedback': 'أرسل ملاحظاتك',
      'feedback_stub': 'شارك أفكارك لنحدد أولويات الميزات القادمة.',
      'settings_shortcut': 'اختصار الإعدادات',
      'help_tip': 'تحتاج مساعدة في ضبط التجربة؟',
      'guides_tip': 'شاهد الشروحات وأفضل الممارسات.',
      'about_team': 'مصمم للمستكشفين باللغتين العربية والإنجليزية.',
      'more_to_explore': 'مزيد للاستكشاف',
      'read_more': 'قراءة المزيد',
      'journey_planner': 'مخطط الرحلة العقارية',
      'journey_progress': 'تقدم الرحلة',
      'journey_progress_hint': 'تتبع خطوات البحث حتى الاختيار النهائي.',
      'journey_steps_completed': 'الخطوات المنجزة',
      'journey_actions': 'الخطوات المتبقية',
      'reset_plan': 'إعادة ضبط الخطة',
      'step_research': 'البحث والإلهام',
      'step_research_desc': 'تصفح التصنيفات والبحث المحفوظ والإرشادات.',
      'step_shortlist': 'قائمة مختصرة للمفضلات',
      'step_shortlist_desc': 'قارن العناصر، دوّن الملاحظات، وضيّق القائمة.',
      'step_schedule': 'جدولة الزيارات',
      'step_schedule_desc': 'اختر الأوقات واحتفظ بالتذكيرات محلياً.',
      'step_notes': 'تسجيل الملاحظات',
      'step_notes_desc': 'اكتب انطباعاتك لكل عنصر لاتخاذ القرار بسرعة.',
      'step_finalize': 'تأكيد الاختيار',
      'step_finalize_desc': 'ثبّت خيارك وراجع النصائح القانونية والأمنية.',
      'budget_planner': 'مخطط الميزانية',
      'budget_hint': 'ضع أهدافك في الحسبان أثناء تصفية الأسعار.',
      'budget_target': 'الهدف الشهري',
      'budget_cta': 'يمكنك التعديل في أي وقت — يخزن محلياً.',
      'planning_tools': 'أدوات التخطيط',
      'planning_intro': 'استخدم قوائم الجاهزية والحاسبة المحلية للبقاء منظماً.',
      'readiness_checklist': 'قائمة الجاهزية',
      'readiness_intro': 'ابق منظماً بالوثائق والزيارات والميزانية قبل القرار.',
      'checklist_progress': 'تقدم القائمة',
      'reset_checklist': 'إعادة تعيين القائمة',
      'task_finance': 'تأكيد الأمور المالية',
      'task_finance_desc': 'انسق ميزانيتك ومدخراتك والموافقات قبل الجولات.',
      'task_documents': 'تحضير الوثائق',
      'task_documents_desc': 'احتفظ بالهوية وإثبات القدرة المالية وملاحظاتك جاهزة.',
      'task_visit_plan': 'تخطيط الزيارات',
      'task_visit_plan_desc': 'رتب الزيارات حسب المدينة والوقت لاستثمار يومك.',
      'task_review': 'المراجعة والقرار',
      'task_review_desc': 'راجع الملاحظات والتقييمات والمقارنات قبل تقديم العرض.',
      'affordability_calculator': 'حاسبة الاستطاعة',
      'home_price': 'سعر العقار',
      'down_payment': 'نسبة الدفعة الأولى',
      'interest_rate': 'نسبة الفائدة',
      'loan_years': 'مدة التمويل (سنة)',
      'estimated_payment': 'القسط الشهري التقديري',
      'calculator_hint': 'اضبط المؤشرات لمعرفة ما يناسب ميزانيتك.',
      'within_budget': 'ضمن هدف ميزانيتك',
      'over_budget': 'فوق هدف ميزانيتك',
      'recommendations': 'تطابقات في نطاقك',
      'no_recommendations': 'لا توجد تطابقات في هذا النطاق بعد',
      'open_checklist': 'فتح قائمة الجاهزية',
      'calculator_shortcut': 'الحاسبة',
      'readiness_shortcut': 'الجاهزية',
      'apply_numbers': 'تطبيق الأرقام',
      'recent_progress': 'آخر التقدم',
      'open_insights': 'فتح لوحة المؤشرات',
      'insights': 'المؤشرات',
      'insights_subtitle': 'راقب البيانات المحفوظة والزيارات والاستعداد المالي.',
      'city_focus': 'تركيز المدن',
      'average_rating': 'متوسط التقييم',
      'listings_count': '{count} قوائم',
      'budget_vs_filters': 'الميزانية مقابل المرشحات',
      'budget_alignment': 'قارن هدفك مع نطاق السعر الحالي.',
      'price_window': 'نطاق السعر',
      'recent_activity': 'النشاط الأخير',
      'insights_empty_recent': 'لا يوجد تصفح حديث بعد',
      'launch_journey': 'افتح مخطط الرحلة',
      'notes_section': 'ملاحظاتي',
      'no_visits': 'لا توجد زيارات مسجلة بعد',
      'app_health': 'صحة التطبيق ونصائح',
      'support_status': 'كل الأنظمة تعمل — لا حاجة لباك اند حالياً.',
      'legal_and_privacy': 'الشروط والخصوصية',
      'privacy_policy': 'سياسة الخصوصية',
      'privacy_body': 'نحتفظ بتفضيلاتك وتصفحك على جهازك فقط.',
      'privacy_local': 'لا توجد خوادم خارجية — بياناتك محليّة.',
      'privacy_saved': 'يمكنك مسح البيانات المحفوظة من الإعدادات في أي وقت.',
      'privacy_contact': 'استخدم طلبات الدعم لطرح أسئلة حول الخصوصية.',
      'terms_of_use': 'شروط الاستخدام',
      'terms_body': 'استخدم التطبيق بشكل مسؤول مع بيانات تجريبية أثناء تطوير الخدمات.',
      'terms_usage': 'المحتوى توضيحي ولا يُعتبر قوائم حقيقية.',
      'terms_content': 'لا تستخدم الصور أو النصوص بشكل غير لائق فهي للتجربة فقط.',
      'terms_changes': 'قد تتغير الميزات والشروط مع التطوير.',
      'safety_and_trust': 'السلامة والثقة',
      'safety_body': 'كن واعياً أثناء الزيارات أو مشاركة المعلومات الشخصية.',
      'safety_expectations': 'أكد المواعيد وابدأ بالاجتماع في أماكن عامة.',
      'safety_reporting': 'أبلغ عن أي سلوك مريب عبر طلب دعم.',
      'safety_updates': 'نحدّث النصائح باستمرار لتناسب أفضل الممارسات.',
      'support_requests': 'طلبات الدعم',
      'new_request': 'طلب جديد',
      'request_title': 'الموضوع',
      'request_topic': 'الفئة',
      'request_details': 'التفاصيل',
      'support_request_hint': 'اشرح ما تحتاجه من مساعدة — يبقى على جهازك.',
      'request_details_hint': 'يرجى إضافة بضع كلمات على الأقل.',
      'request_saved': 'تم حفظ الطلب محلياً',
      'request_removed': 'تم حذف الطلب',
      'support_empty_title': 'لا يوجد طلبات دعم بعد',
      'support_empty_body': 'سجّل أسئلتك أو احتياجاتك هنا دون مغادرة التطبيق.',
      'mark_resolved': 'وضعه محلولاً',
      'mark_pending': 'وضعه قيد المتابعة',
      'required_field': 'هذا الحقل مطلوب',
      'send': 'إرسال',
    }
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('ar'), Locale('en')];
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
